### ISSUE TITLE
A Laravel Mix extension for Webpack bundle analyzer support

### ISSUE THREAD

**Issue by MaximVanhove** [mvdnbrk/laravel-mix-docs#11]
Hello,

I made a wrapper for Webpack Bundle Analyzer: [https://www.npmjs.com/package/laravel-mix-bundle-analyzer](https://www.npmjs.com/package/laravel-mix-bundle-analyzer)

You can list it on your extensions page if you want to.

**Comment by mvdnbrk** [comment]
Toegevoegd :smile:

https://laravel-mix.com/extensions/bundle-analyzer
