### ISSUE TITLE
Mix Extension: laravel-mix-copy-watched

### ISSUE THREAD

**Issue by dsktschy** [mvdnbrk/laravel-mix-docs#12]
Hello.

I made a extended copy method.

This method provides the following.

- Watching for not only changes but also additions and deletions
- Keeping a hierarchical structure with the base option (like Gulp)

npm: https://www.npmjs.com/package/laravel-mix-copy-watched
GitHub: https://github.com/dsktschy/laravel-mix-copy-watched

**Comment by mvdnbrk** [comment]
Thanks, added [here](https://laravel-mix.com/extensions/copy-watched).
