### ISSUE TITLE
Mix Extension: laravel-mix-polyfill

### ISSUE THREAD

**Issue by scottcharlesworth** [mvdnbrk/laravel-mix-docs#14]
I've made a Laravel Mix extension for Babel Polyfill.

The extension allows you to easily specify:
- if the extension is enabled
- how polyfills are handled
- environments you support/target as a browserslist-compatible query or as an object

npm: https://www.npmjs.com/package/laravel-mix-polyfill
GitHub: https://github.com/scottcharlesworth/laravel-mix-polyfill

**Comment by mvdnbrk** [comment]
Thanks!

Added [here](https://laravel-mix.com/extensions/polyfill).
