### ISSUE TITLE
Mix extension: laravel-mix-imagemin

### ISSUE THREAD

**Issue by CupOfTea696** [mvdnbrk/laravel-mix-docs#18]
Hi,

I've made a laravel mix extension for imagemin.

npm: https://www.npmjs.com/package/laravel-mix-imagemin
GitHub: https://github.com/CupOfTea696/laravel-mix-imagemin

**Comment by mvdnbrk** [comment]
Thanks!

Added [here](https://laravel-mix.com/extensions/imagemin)
