### ISSUE TITLE
No mention of sourceMaps() method

### ISSUE THREAD

**Issue by rdarcy1** [mvdnbrk/laravel-mix-docs#34]
I couldn't see any reference to the `mix.sourceMaps()` method in the docs – perhaps something that could be included?

For reference, it is included on the Laravel docs page: https://laravel.com/docs/5.8/mix

**Comment by mvdnbrk** [comment]
Thanks, yes that could certainly be added to the docs :)

**Comment by mvdnbrk** [comment]
@rdarcy1 `mix.sourceMaps()` seems to be buggy at the moment. See this [issue](https://github.com/JeffreyWay/laravel-mix/issues/1793).

So I am not including this now in the docs before the issue is resolved.

**Comment by rdarcy1** [comment]
Ah understood. I was originally looking for the docs because I was having issues with it not generating – looks like that issue explains why!
