### ISSUE TITLE
Extension: laravel-mix-svg-vue

### ISSUE THREAD

**Issue by danielstgt** [mvdnbrk/laravel-mix-docs#36]
I've created an extension to automatically use optimized SVG's via SVGO with Vue.js. One benefit compared to similar solutions is, that no wrapping html element is added around the inlined SVG.

Title: Laravel Mix SVG Vue
Description: Extension to inline SVG files with Vue.js and optimize them automatically with SVGO.
Installation: npm i laravel-mix-svg-vue
GitHub Repo: https://github.com/danielstgt/laravel-mix-svg-vue
NPM: https://www.npmjs.com/package/laravel-mix-svg-vue

Would appreciate a listing of the extension on your page.

**Comment by mvdnbrk** [comment]
Thanks!

Added: https://laravel-mix.com/extensions/svg-vue
