### ISSUE TITLE
Laravel Mix clean-css

### ISSUE THREAD

**Issue by marceickhoff** [mvdnbrk/laravel-mix-docs#51]
I created an extension that provides easy integration of [clean-css](https://github.com/jakubpawlowicz/clean-css).

https://github.com/marceickhoff/laravel-mix-clean-css
https://www.npmjs.com/package/laravel-mix-clean-css

I would appreciate if it would be listed on the extensions page.

**Comment by mvdnbrk** [comment]
Hi thanks!

Added here: https://laravel-mix.com/extensions/clean-css
