### ISSUE TITLE
Laravel Mix Modernizr

### ISSUE THREAD

**Issue by marceickhoff** [mvdnbrk/laravel-mix-docs#52]
Hey! I created another extension that allows easy configuration, creation and management of custom Modernizr builds in a Laravel Mix project.

https://www.npmjs.com/package/laravel-mix-modernizr
https://github.com/marceickhoff/laravel-mix-modernizr

**Comment by mvdnbrk** [comment]
Thanks!

Added: https://laravel-mix.com/extensions/modernizr
