### ISSUE TITLE
Add laravel-mix-remove-flow-types

### ISSUE THREAD

**Issue by janpantel** [mvdnbrk/laravel-mix-docs#53]
This package allows for use of flowtypes within javascript files.

NPM package: https://www.npmjs.com/package/laravel-mix-remove-flow-types
Repository: https://github.com/janpantel/laravel-mix-remove-flow-types

**Comment by mvdnbrk** [comment]
Thanks.

Added: https://laravel-mix.com/extensions/remove-flow-types
