### ISSUE TITLE
Versioning only ever takes place in production

### ISSUE THREAD

**Issue by knowler** [mvdnbrk/laravel-mix-docs#54]
[This clause](https://github.com/mvdnbrk/laravel-mix-docs/blob/5.0/versioning.md#optionally-versioning-files) is misleading since [versioning only ever takes place in production](https://github.com/JeffreyWay/laravel-mix/blob/ddd3834eae01bb2d40fe186d8a72ab23d8830f51/src/components/Version.js#L31-L39). I propose that the clause is removed and a note stating this fact is added.

**Comment by mvdnbrk** [comment]
Calling ` mix.version()` and `npm run dev` will version the files in the `mix-manifest.json` file.
