### ISSUE TITLE
Laravel mix compress Images

### ISSUE THREAD

**Issue by tsecher** [mvdnbrk/laravel-mix-docs#55]
Hi, I created a mix extension that provides tools  to compress images through the compress_images tool. You can find it here : 
https://www.npmjs.com/package/laravel-mix-compress-images
https://bitbucket.org/thomasse/laravel-mix-compress-images/src/1.x/

Regards,

**Comment by mvdnbrk** [comment]
Thanks.
https://laravel-mix.com/extensions/compress-images
