### ISSUE TITLE
vuetifyjs extensions.

### ISSUE THREAD

**Issue by Nothing-Works** [mvdnbrk/laravel-mix-docs#57]
vuetifyjs with mix is a bit tricky to setup, would accept that extensions?

**Comment by mvdnbrk** [comment]
You are welcome to submit an extension

**Comment by Nothing-Works** [comment]
https://github.com/Nothing-Works/vuetifyjs-mix-extension

https://www.npmjs.com/package/vuetifyjs-mix-extension

There you go. it's mix with vuetify.

**Comment by Nothing-Works** [comment]
@mvdnbrk  
https://github.com/Nothing-Works/vuetifyjs-mix-extension

https://www.npmjs.com/package/vuetifyjs-mix-extension

There you go. it's mix with vuetify. @mvdnbrk

**Comment by mvdnbrk** [comment]
@Nothing-Works Thanks!

Added: https://laravel-mix.com/extensions/vuetifyjs-mix-extension
