### ISSUE TITLE
Laravel Mix CSS Partial

### ISSUE THREAD

**Issue by abhisheksatre** [mvdnbrk/laravel-mix-docs#58]
Hi! I have created an extension that provides CSS partials supports in Mix. 

https://github.com/abhisheksatre/laravel-mix-css-partial
https://www.npmjs.com/package/laravel-mix-css-partial

It would be great if it can be listed on the extensions page.

**Comment by mvdnbrk** [comment]
Thanks!

Added: https://laravel-mix.com/extensions/css-partial
