### ISSUE TITLE
Laravel Mix JS Partials

### ISSUE THREAD

**Issue by abhisheksatre** [mvdnbrk/laravel-mix-docs#59]
Hi! 
I have created an extension that provides JS partials supports in Mix.

https://github.com/abhisheksatre/laravel-mix-js-partial
https://www.npmjs.com/package/laravel-mix-js-partial

It would be great if it can be listed on the extensions page.

**Comment by mvdnbrk** [comment]
Thanks!

Added: https://laravel-mix.com/extensions/js-partial
