### ISSUE TITLE
Laravel Mix BrowserSync Multi

### ISSUE THREAD

**Issue by nmfzone** [mvdnbrk/laravel-mix-docs#61]
This extension provides support for creating multiple BrowserSync instance.

https://github.com/nmflabs/laravel-mix-browser-sync-multi
https://www.npmjs.com/package/laravel-mix-browser-sync-multi

Related topic: https://github.com/BrowserSync/browser-sync/issues/172#issuecomment-74232625

**Comment by mvdnbrk** [comment]
Thanks!

Added: https://laravel-mix.com/extensions/browser-sync-multi
