### ISSUE TITLE
Laravel Mix Code Splitter

### ISSUE THREAD

**Issue by zhorton34** [mvdnbrk/laravel-mix-docs#65]
![Version](https://img.shields.io/npm/v/laravel-mix-code-splitter.svg?color=success&logo=npm)
[![Maintenance](https://img.shields.io/badge/Maintained%3F-yes-green.svg?color=success&logo=github)](https://GitHub.com/Naereen/StrapDown.js/graphs/commit-activity)

---

##### [<img src="https://img.icons8.com/cute-clipart/17/000000/github.png"></img> Github Repo ](https://github.com/zhorton34/laravel-mix-code-splitter)

---

# <img src="https://img.icons8.com/fluent/38/000000/download.png"/> Install

---

### <img src="https://img.icons8.com/color/21/000000/npm.png"/>  NPM

```bash
npm install --save-dev laravel-mix-code-splitter
```

### <img src="https://img.icons8.com/color/21/000000/clew.png"/> Yarn

```bash
yarn add laravel-mix-code-splitter --save
```

**Comment by mvdnbrk** [comment]
Added: https://laravel-mix.com/extensions/code-splitter
