### ISSUE TITLE
Single File Blade Components

### ISSUE THREAD

**Issue by abhisheksatre** [mvdnbrk/laravel-mix-docs#69]
Hi! I have created an extension that lets you use blade components like Vue's single-file components.

Github link: https://github.com/abhisheksatre/single-file-blade-components

NPM link: https://www.npmjs.com/package/single-file-blade-components

It would be great if it can be listed on the extensions page.

**Comment by mvdnbrk** [comment]
Added here: https://laravel-mix.com/extensions/single-file-blade-components
