### ISSUE TITLE
Laravel Mix extension for AngularJS $templateCache

### ISSUE THREAD

**Issue by rafaelmussi** [mvdnbrk/laravel-mix-docs#70]
Hi, 
I created an extension that concatenates, registers and combines AngularJS HTML templates in the $templateCache.

https://github.com/rafaelmussi/laravel-mix-angular-templatecache
https://www.npmjs.com/package/laravel-mix-angular-templatecache

**Comment by mvdnbrk** [comment]
Thanks, added!

https://laravel-mix.com/extensions/angular-templatecache
