### ISSUE TITLE
Laravel Mix Serve plugin

### ISSUE THREAD

**Issue by mikesaintsg** [mvdnbrk/laravel-mix-docs#73]
A new plugin that can run **custom** serve commands, and of course by default runs the `php artisan serve` command.

It runs after compilation and within the same shell. 

Users can configure whether to include or exclude the output from the server. In case they are not interested in the server output and do not want to lose sit of their compiled mix output.

They can even configure for the output to be logged once to solely retrieve the first output, which in the case of Laravel is to see the output that the server has started.

See my package on github and npm in the links below:
https://github.com/mikesaintsg/laravel-mix-serve
https://www.npmjs.com/package/laravel-mix-serve

**Comment by mvdnbrk** [comment]
Thanks, added here: https://laravel-mix.com/extensions/mikesaintsg-serve
