### ISSUE TITLE
Vue SVG Icon Extension

### ISSUE THREAD

**Issue by excellentingenuity** [mvdnbrk/laravel-mix-docs#8]
Here is an extension for using svg's as icons via a vue component. It uses the mix webpack config and processing to dynamically select and render the svg from a filename in a directory. NPM:https://www.npmjs.com/package/laravel-mix-vue-svgicon  Githb:https://github.com/excellentingenuity/laravel-mix-vue-svgicon

**Comment by mvdnbrk** [comment]
Added 😃 

https://laravel-mix.com/extensions/vue-svgicon
