### ISSUE TITLE
Laravel Mix Compress 

### ISSUE THREAD

**Issue by selim13** [mvdnbrk/laravel-mix-docs#81]
Hello!
Just published the extension to compress assets with [CompressionWebpackPlugin](https://webpack.js.org/plugins/compression-webpack-plugin/).

Repo: https://github.com/selim13/laravel-mix-compress
Package: https://www.npmjs.com/package/laravel-mix-compress

Usage:
```sh
npm install --save-dev laravel-mix-compress
```

```js
// webpack.mix.js
const mix = require('laravel-mix');
require('laravel-mix-compress');

mix.js('src/app.js', 'js');
mix.css('src/app.css', 'css');
mix.compress();
```

**Comment by mvdnbrk** [comment]
Sorry for my late reply but I have added your extension:

https://laravel-mix.com/extensions/compress
