### ISSUE TITLE
New extension: Laravel Mix Replace In File

### ISSUE THREAD

**Issue by andreg** [mvdnbrk/laravel-mix-docs#83]
Hi,

I have created an extension, that allows string replacement within a file, since the one listed in the Extensions page doesn't seem to be working anymore.

Here's the link to the NPM package: https://www.npmjs.com/package/laravel-mix-replace-in-file

It'd be great to have the extension listed in the Extensions page.

Thank you!

**Comment by mvdnbrk** [comment]
Sorry for my late reply but I have added your extension !

https://laravel-mix.com/extensions/replace-in-file
