### ISSUE TITLE
Laravel Mix Eta Plugin

### ISSUE THREAD

**Issue by otowa552** [mvdnbrk/laravel-mix-docs#87]
Hi.
I have created the Eta plugin for Laravel Mix.
[Eta](https://github.com/eta-dev/eta) is a light and easy to use JS template engine similar to Ejs.
It only supports HTML exporting yet, but I plan to add more features later on.
It would be great to have it on the extension list.
Thanks.

https://www.npmjs.com/package/laravel-mix-eta

**Comment by mvdnbrk** [comment]
Sorry for my late reply but I have added your extension:

https://laravel-mix.com/extensions/eta

Thanks!
