### ISSUE TITLE
Laravel Mix Twig extension

### ISSUE THREAD

**Issue by gsusg** [mvdnbrk/laravel-mix-docs#89]
Hi, I wrote an extension for personal use but some users are [asking](https://github.com/ideil/laravel-mix-twig/issues/27#issue-1158243154) to add it to the official Laravel Mix page.

[Laravel Mix extension that generates HTML from Twig templates.](https://github.com/ideil/laravel-mix-twig)

**Comment by mvdnbrk** [comment]
Thanks, added!

https://laravel-mix.com/extensions/twig
