### ISSUE TITLE
Mix extension: laravel-mix-eslint-config

### ISSUE THREAD

**Issue by patrickcurl** [mvdnbrk/laravel-mix-docs#9]
I've made a more modular/configurable version of the laravel-mix-eslint  extension.

at: https://www.npmjs.com/package/laravel-mix-eslint-config 

The major difference is for the previous package you could only pass in the config.options key, if you wanted to customize for react or something else...like pass in js,vue,jsx to the config.test you couldn't. This updated version let's you modify the entire config object for eslint-loader.

You can also specify which plugins to use for eslint (vue|react) and it'll add those as dependencies.

**Comment by mvdnbrk** [comment]
Added [here](https://laravel-mix.com/extensions/eslint-config) :smile:
