### ISSUE TITLE
Laravel Mix Swc

### ISSUE THREAD

**Issue by d8vjork** [mvdnbrk/laravel-mix-docs#91]
Laravel mix extension that replaces Babel with SWC (made in Rust) so it transpile and polyfill code much faster.

I needed it for multiple projects, one of them is huge so that's the reason behind its creation.

https://github.com/open-southeners/laravel-mix-swc

**Comment by mvdnbrk** [comment]
Thanks! Added: https://laravel-mix.com/extensions/swc
