### ISSUE TITLE
Laravel mix webpack config extension

### ISSUE THREAD

**Issue by MohamedLamineAllal** [mvdnbrk/laravel-mix-docs#94]
Laravel mix extension that adds a function to listen to config readiness. And give access to the object and the `circularStringify()` function. So people can do anything with it including writing the config to a file. At the same time, it does patch `dump()` and `dumpWebpackConfig()` to support the same callback as extra.

https://github.com/MohamedLamineAllal/laravel-mix-webpack-config#readme

https://www.npmjs.com/package/laravel-mix-webpack-config

npm published and tested.

**Comment by mvdnbrk** [comment]
Thanks! Added: https://laravel-mix.com/extensions/webpack-config
