### ISSUE TITLE
Laravel mix listen extension

### ISSUE THREAD

**Issue by MohamedLamineAllal** [mvdnbrk/laravel-mix-docs#95]
An extension that gives access to the underlying dispatcher `listen()` function. To hook to all internal events. All the events were well documented as well.

https://github.com/MohamedLamineAllal/laravel-mix-listen
https://www.npmjs.com/package/laravel-mix-listen

npm published and well tested.

**Comment by mvdnbrk** [comment]
Thanks! Added: https://laravel-mix.com/extensions/listen
